# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

# Triggers the workflow on push or pull request events
# but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
     matrix:
       os: [macos-latest,ubuntu-latest]
       python-version: [3.6]
    steps:
    # checks-out repository
    - uses: actions/checkout@v2
    - name: Set up Python environment
      # This action sets up a Python environment.
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt
        pip install click numpy scipy pandas matplotlib joblib
    - name: Lint with flake8
      run: |
        make lint
#    - name: Test with pytest
#      run: |
#       make test
    - name: Generate coverage report
      run: |
        make coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        env_vars: ${{ matrix.os }},${{ matrix.python-version }}
        fail_ci_if_error: true
        files: ./coverage.xml
#        flags: unittests
#        name: codecov-umbrella
#        path_to_write_report: ./coverage/codecov_report.txt
#        verbose: true

